### ISSUE TITLE
No captions, no transcript on 3.091 fall 2018

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#1518] opened 2022-10-05 16:46 UTC
### Steps to Reproduce

See, for example, https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/resources/lecture-1/

or https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/resources/carbon-dioxide-concentration-lec28/

### Expected Behavior

- There should be an interactive transcript player. 
- There should be a button to turn on captions 

### Actual Behavior

- no transcript
- no captions 

### Screenshot or Screencast

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/430126/194116220-856e7c73-5d1e-403c-95a3-2d40a2b5d255.png">

**Comment by fakhar-ud-din** [comment] 2023-02-14 08:48
Hey @pdpinch 

I am working on the fix, but seems like I do not have access to the [content drive yet](https://drive.google.com/drive/u/0/folders/0AIZerpz9jimTUk9PVA).

The captions are unavailable since we do not have a path set for them (I have attached a screenshot for this). Could you please update me with the status regarding the access, so I could proceed with the fix?


![Screenshot 2023-02-14 at 1 48 20 PM](https://user-images.githubusercontent.com/68846543/218685000-185353ce-38ce-409f-b40e-c659a8e88f6a.png)

Thank You

**Comment by pdpinch** [comment] 2023-02-20 02:09
I will give you access, but I don't think you're going to find the missing files on gdrive. This is a legacy course, and the files should have been imported directly to S3.

**Comment by fakhar-ud-din** [comment] 2023-02-20 13:56
Hey @pdpinch 

I have tested this locally by using random lecture's caption file, and setting the `RESOURCE_BASE_URL` to the s3 bucket link. This configuration is working fine locally. 
I think we do not have `RESOURCE_BASE_URL` on production, which causes the conditional rendering of the captions to fail.

I am still looking into this, and will keep you updated.

Thank you

**Comment by fakhar-ud-din** [comment] 2023-02-24 13:14
I have successfully reproduced the issue locally, but I am not quite certain whether I am headed in the right direction.

### Steps to reproduce locally
1. Clone 3.091 fall 2018
2. Comment out `RESOURCE_BASE_URL` in the **env** file
3. Comment out `RESOURCE_BASE_URL` config in the **env.ts** file
4. Start the course, `yarn start course 3.091-fall-2018`
5. Navigate to http://localhost:3000/resources/lecture-1/
6. The captions button and transcript box should be unavailable

**NOTE:**
1. The `video_captions_file` in `ocw-content-rc/3.091-fall-2018/content/resources/lecture-1.md` should be **_null_**
2. If either `RESOURCE_BASE_URL` and/ or `video_captions_file` is set to something, the captions and transcripts become available

**Comment by ChristopherChudzicki** [comment] 2023-02-27 14:12
I want to mention that this is not limited to 3.091-fall-2018. 

Here are a few more examples of videos that DO have high-quality transcripts on YouTube, but do NOT have associated transcripts on OCW.
- (already mentioned) https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/video_galleries/lecture-videos/
- (all recitation videos, I believe) https://ocw.mit.edu/courses/6-041sc-probabilistic-systems-analysis-and-applied-probability-fall-2013/resources/rooks-on-a-chessboard/
- (all videos?) https://ocw.mit.edu/courses/5-80-small-molecule-spectroscopy-and-dynamics-fall-2008/resources/lecture-3/
- (all recitation videos?) https://ocw.mit.edu/courses/6-01sc-introduction-to-electrical-engineering-and-computer-science-i-spring-2011/resources/recitation-1-object-oriented-programming/

@pt2302 @gumaerc and @abeglova have discussed these a little bit, but to my knowledge no concrete plan has been formed. (@pt2302 may corret me when he's back from vacation). Roughly, I believe we were thinking
- we think these videos have 3play captions
- 3play knows the YouTube ids
- ocw studio knows the YouTube Ids of the videos. Let's try to look up the 3play captions by youtube id.

I haven't used the 3play APIs myself, but that is my understanding of what @pt2302 @abeglova @gumaerc and I have discussed in the past.

Here is a list of OCW resources that do not have transcripts https://gist.github.com/ChristopherChudzicki/25a0310d2de4a568d6b19e8f009c86a8. These is ALL videos that do not have transcripts **in ocw**. Some do have transcripts on YouTube, some do not. Some have no sound at all.

**Comment by fakhar-ud-din** [comment] 2023-03-01 13:53
Hey @ChristopherChudzicki 

Thank you for the detailed response.
Yes we actually have missing caption files for majority of the videos, and this issue is wide-spread to other courses as well.

My concern is related to the UI elements of captions and transcripts, since those should be rendering despite the availability of the captions and transcript files. Right?

The UI elements tends to disappear only when we are missing `RESOURCE_BASE_URL` or [This](https://github.com/mitodl/ocw-hugo-themes/blob/b79dc6763c2c5a6ae43861f8f872f03ff7489b62/base-theme/layouts/partials/video.html#L2) is not set.

What are your thoughts on this?

**Comment by ChristopherChudzicki** [comment] 2023-03-06 14:38
> Yes we actually have missing caption files for majority of the videos,

I think it's more like ~15% of videos, but still more than just this course.

> My concern is related to the UI elements of captions and transcripts, since those should be rendering despite the availability of the captions and transcript files. Right?

IMO, it's fine not to show the "CC" button if there are no captions. Similarly with the expandable transcript. If there's no transcript, no need to show the "Transcript" button. (If we do show it, and it's empty, then that's confusing. So if we do show it, we would want to show "No transcript available" or something. Might as well just not show it.)

This issue, as I understand it, is "Transcripts for 3.091 (and several other courses) used to exist in legacy ocw, but do not exist in current ocw. Let's figure out how to make those transcripts available in ocw-next."

**Comment by fakhar-ud-din** [comment] 2023-03-08 13:19
> IMO, it's fine not to show the "CC" button if there are no captions. Similarly with the expandable transcript. If there's no transcript, no need to show the "Transcript" button. (If we do show it, and it's empty, then that's confusing. So if we do show it, we would want to show "No transcript available" or something. Might as well just not show it.)

 @ChristopherChudzicki  It makes sense to not show those UI elements in case of unavailability of the transcripts and captions. Not sure, where to find the legacy ocw config and files?

**Comment by ChristopherChudzicki** [comment] 2023-03-08 15:04
@pdpinch @fakhar-ud-din Regarding SRT caption files for 3.091-2018, they do exist. For example
```
lecture 1
  video:
    https://github.mit.edu/mitocwcontent/3.091-fall-2018/blob/main/content/resources/lecture-1.md
  srt caption:
    https://github.mit.edu/mitocwcontent/3.091-fall-2018/blob/main/content/resources/ao41frjfgvq.md
  transcript:
    https://github.mit.edu/mitocwcontent/3.091-fall-2018/blob/main/content/resources/ao41frjfgvq-1.md
```
The video is explicitly associated with the transcript but not the SRT. However, the SRT filenames appear to be a lowercased version of the youtube ID, which does exist in the video file metadata.

I believe all videos in 3.091 have SRT captions (there are 92 srt files and 82 video files in the course, so, probably...).

**This is not necessarily true for other courses with missing captions**, so maybe we have multiple root causes for missing captions. E.g., `5-80-small-molecule-spectroscopy-and-dynamics-fall-2008` appears to have no caption files, srt or vtt. 

@fakhar-ud-din I found the above information via SQL queries on RC (which was recently synced with prod). Querying models in Django shell would also work.

**Comment by ChristopherChudzicki** [comment] 2023-03-08 15:07
As for what to do: I think "convert SRT -> VTT" would work fine for 3.091 2018. But again, there are more courses whose captions DO appear to exist on youtube, but do not have SRT files. A more general 3play approach (like sketched in https://github.com/mitodl/ocw-studio/issues/1518#issuecomment-1446392041) might be able to address the problem for more courses.

**Comment by pdpinch** [comment] 2023-03-09 01:55
This is great folks. So the captions exist, they are probably in our 3play account and we have code for looking them up and fetching them. 

How about we start with a management command that tries to fetch the .vtt caption file from 3play and add it the video as a new resource, using the functions Paul mentioned? 

Feel free to suggest alternatives.

**Comment by fakhar-ud-din** [comment] 2023-03-10 13:14
Thank you for the suggestions @pt2302 @ChristopherChudzicki 
I believe, I do not have the database dump locally, so I could not confirm using the django shell.

I will be moving forward with what @pt2302 suggested and will work on a management command which could fetch and sync available captions and transcripts.

**Comment by fakhar-ud-din** [comment] 2023-03-13 13:17
I have been investigating the issue, and seems like we already have a celery in place which runs the methods in case of missing captions and transcripts.
The following code, executes a celery which attempts to fetch existing transcript and captions, and if not found, utilises the 3play api to get them.
https://github.com/mitodl/ocw-studio/blob/c0f96b807ad78dbf4873bf46065337c80d47dd86/main/settings.py#L699

I think we might have to go with this


> As for what to do: I think "convert SRT -> VTT" would work fine for 3.091 2018. 

What do you think about this, @ChristopherChudzicki ?

**Comment by fakhar-ud-din** [comment] 2023-03-14 12:37
Seems like the celery is working fine.

> https://github.com/mitodl/ocw-studio/blob/210b230d65ecc1cee601054e64cb6adc1cf131e2/videos/threeplay_api.py#L153
> 
> Assuming most/all legacy captions are on 3Play, this seems like the most straightforward solution.

I tried running the above code in the heroku's ocw-studio (production) shell, and got empty results. Moreover, the `3.091 fall 2018` seems to be missing when running the following queries 

- `Video.objects.filter(source_key__icontains="3-091")`
- `Video.objects.filter(website__name="3-091-introduction-to-solid-state-chemistry-fall-2018")`

<img width="1716" alt="Screenshot 2023-03-14 at 4 58 01 PM" src="https://user-images.githubusercontent.com/68846543/225000773-0c91c073-f3ef-43e6-8c11-c8b2c3cc70ba.png">

<img width="1762" alt="Screenshot 2023-03-14 at 5 32 25 PM" src="https://user-images.githubusercontent.com/68846543/225002710-8cc023b3-2c2e-45ce-b651-d7c943bf3a77.png">


I am still looking into it, will keep you updated

**Comment by fakhar-ud-din** [comment] 2023-03-14 14:32
I have found a potential solution for this.

Found the video related content in `WebsiteContent`. And all those missing the captions and transcripts actually does not have a defined parent (Website, 3-091-introduction-to-solid-state-chemistry-fall-2018 in this case).

Based on the content, we will making Website and Video objects for that which will establish the missing link for all the legacy transferred videos. I am starting to confirm my findings, and will proceed with the implementation shortly.

**Comment by fakhar-ud-din** [comment] 2023-03-16 12:22
Hey @pdpinch / @pt2302 

I ssh'ed into the heroku shell for ocw-studio, and I filtered the current website (_3-091-introduction-to-solid-state-chemistry-fall-2018_) which had no `Video` object. 

![Screenshot 2023-03-16 at 4 40 26 PM](https://user-images.githubusercontent.com/68846543/225611577-b986dd4f-6392-4ac8-9bb5-30232041c945.png)

> If it exists, we can download the captions/transcript and associate them with a given video by something like this function:
> 
> https://github.com/mitodl/ocw-studio/blob/210b230d65ecc1cee601054e64cb6adc1cf131e2/videos/threeplay_api.py#L153

The above will not work, since there is no Video object present to associate the fetched transcripts to. Moreover, when requested the 3play transcripts using this course's youtube_ids, majority of them had an empty data object.

![Screenshot 2023-03-16 at 4 40 50 PM](https://user-images.githubusercontent.com/68846543/225612880-92ef0f7a-223a-43fe-a230-5beee4eeec76.png)


I also queried the database for  `video_captions_file` from the video resources of existing website's content.
Only 122 video resources had `video_captions_file`

![Screenshot 2023-03-16 at 4 59 33 PM](https://user-images.githubusercontent.com/68846543/225610513-548fd87d-4693-4131-a01e-bd75d3bb84e1.png)


My proposed solution is, to make a management command, which creates `Video` objects for a website, if not already present, then updates the video object's details (_webvtt_transcript_file, website, pdf_transcript_file_) with existing caption files. If we are unable to find a caption file for some video resource, we will incorporate a request to 3play and will update the video object details with received response.

Please let me know if I missed anything

Thank You

**Comment by fakhar-ud-din** [comment] 2023-03-16 20:03
Oh then that simplifies it. Thank you
I will proceed with the solution and make PR by EOD today

**Comment by pdpinch** [comment] 2023-03-16 21:18
> If we are unable to find a caption file for some video resource, we will incorporate a request to 3play and will update the video object details with received response.

How will you try to find the caption file for the video resource? If it is very complicated, then it might be easier to just make the request to 3Play.

**Comment by pdpinch** [comment] 2023-05-02 17:11
I don't think the management command has been run yet on this course, 3.091 Fall 2018, so I'm reopening this issue until it has been fixed up.

**Closed** 2023-05-18 06:49 UTC
Labels: legacy
