### ISSUE TITLE
21W.758 2013 - Missing in Prod, but I see it in RC

### ISSUE THREAD

**Issue by dseaton** [mitodl/ocw-studio#1113] opened 2022-03-11 17:15 UTC
### Steps to Reproduce

Course on RC: https://ocw-studio-rc.odl.mit.edu/sites/21w-758-genre-fiction-workshop-spring-2013/

404 on Prod: https://ocw-studio.odl.mit.edu/sites/21w-758-genre-fiction-workshop-spring-2013/

### Expected Behavior

This course should be available to edit in ocw-studio prod.

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/1703442/157915325-6712e0c1-9aeb-42bf-98cd-45b7d9945656.png)

**Comment by pdpinch** [comment] 2022-03-15 21:32
This is a duplicate of https://github.com/mitodl/ocw-to-hugo/issues/470

**Closed by pdpinch** 2022-03-15 21:32 UTC
